# -*- coding: utf-8 -*-
"""Deliverable (8).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZF3HbycFu2lOSxbh3Koxq1ijbB9VUyO-
"""

import numpy as np

def random_list(size):
  list = []
  for i in range(size):
    list.append(np.random.randint(10,50))
  return list

def sum_random (list):
  sum = 0
  for i in range(len(list)):
    sum = sum + list[i]
  return sum

n = int(input("Enter an integer: "))

while True:
  if n < 5 or n > 15:
    n = int(input("Enter an integer in between 5 and 15: "))
  else:
   break

MyList = random_list(n)
MyList

MySum = sum_random(MyList)
MySum

MyList2 = np.random.randint(10,50,n)
MyList2

MySum2 = sum(MyList2)
MySum2